### ISSUE TITLE
When finding errors should exit with status code 1

### ISSUE THREAD

**Issue by tteltrab** [yvanavermaet/gulp-htmllint#1]
Here's a forced example of running the the task.  It successfully finds problems in the files, but only exits with status code 0:

![image](https://cloud.githubusercontent.com/assets/1487463/8083188/caa327f6-0f50-11e5-930b-538ad9c3fd1f.png)

Trying to fail a build automatically if this fails.  I think it should exit with status code 1.  Here's my code:

```
gulp.task("htmllint", function () {
    var htmllint = require("gulp-htmllint");

    return gulp.src(paths.html)
        .pipe(htmllint({
            maxerr: false,
            htmllintrc: true
        }));
});
```

**Comment by Ristaaf** [comment]
Would probably break some uses unless hidden behind a flag somehow, however with reporter support (pull request #3 ) you could do:

```
gulp.task("htmllint", function () {
    var htmllint = require("gulp-htmllint");

    return gulp.src(paths.html)
        .pipe(htmllint({
            maxerr: false,
            htmllintrc: true
        },myreporter));
});

function myreporter(file, issues) {
    gutil = require('gulp-util');
    var out = [];
    if (issues.length > 0) {
        out.push('\n' + file.path);
    }
    
    issues.forEach(function(issue) {
        out.push(gutil.colors.red('line ' + issue.line + '\tcol ' + issue.column + '\t' + (issue.msg || htmllint.messages.renderIssue(issue)) + ' (' + issue.code + ')'));
    });
    if (out.length > 0) {
      gutil.log(out.join('\n'));
      process.exitCode=1;
    }
}
```

This happens to be the default reporter copied from the source code (when specifying a reporter according to my pull request it will turn off the default one, this might be improved upon also, so that you would not have to write a complete reporter to add the exitCode)

**Comment by yvanavermaet** [comment]
My deepest apologies for not replying any time sooner.

This plugin should help people with the use of htmllint, so I'm all for adding a parameter to override the "default" behaviour of htmllint.

Will check this out tomorrow!
