### ISSUE TITLE
Feature Request: configuration format more flexible

### ISSUE THREAD

**Issue by RobDesideri** [yvanavermaet/gulp-htmllint#17]
Hi,
can be a good thing to support more configurations format and path (ie, a file in the user home dir).
Already exists a good project, [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), for implements these features.
Can you add it to project?

If you want, i can help.

**Comment by yvanavermaet** [comment]
Hi @RobDesideri 

Been a while since I've worked on the project. My apologies for the late reply.
I'll look into the current configuration and see if this is worth adding to the tool.

Could you tell me the use case for adding it? Why do you need it specifically?

Thanks for the suggestion.

Kind regards,
Yannick

**Comment by RobDesideri** [comment]
Hi @yvanavermaet 

It's been a while and I honestly don't remember the specific use case.
However, I believe that the request is related to the possibility of having a configuration file at the user level, without having to load a specific configuration file in each project.

**Comment by yvanavermaet** [comment]
At this point 2 options are available: .htmllintrc (as used by the htmllint plugin) and passing the options directly to gulp-htmllint (in your gulpfile).

I'm currently not tempted to implement this as I can't see the use case of someone wanting to have 1 htmllintrc file for all his/her projects.

I was already thinking of a feature where you could have a .htmllinrc file per directory (to apply different rules to different directories), and this is just the opposite of that (not saying that we can't have both though).
