### ISSUE TITLE
Reporter Support

### ISSUE THREAD

**Issue by Ristaaf** [yvanavermaet/gulp-htmllint#2]
There should be an option to add a reporter to the call, like so:

.pipe(htmllint(options,reporter))

with the signature reporter(file, issues)

**Comment by yvanavermaet** [comment]
I'll take a look at your PR tomorrow. Thanks for the effort and I'll get back to you asap.

**Comment by yvanavermaet** [comment]
This should be ok now! Had to update some documentation and added a few fixes here and there!

Think I forgot to mention #2 in the commit message, so going to close this one manually :-)

**Comment by sujanamadhav** [comment]
Hi,
I see that only single html file name is printed for all the errors under src directory.Did anyone face it earlier? Is there a way to get each html name and its respective issues reported?
