### ISSUE TITLE
Data missing for plugins following `gulp-htmllint`

### ISSUE THREAD

**Issue by forrestab** [yvanavermaet/gulp-htmllint#24]
I have a need to summarize the results of `gulp-htmllint`, similar to what `eslint` does with "# problems" after the rule checks are finished. For this I created a simple plugin function using `through2` that would read the `htmllint` property on the `file` object and format the totals by rule. This worked great a couple of days ago and after upgrading to 0.0.15 I am no longer able to see any data in my plugin function after `gulp-htmllint`.

I could be wrong, but I believe I narrowed down the issue to the callbacks in this commit https://github.com/yvanavermaet/gulp-htmllint/commit/839689e368e7c62d80fcf028a34b26cca51bf420. Here I noticed callbacks were changed from `cb(null, file);` (0.0.14) to `cb();` (0.0.15).

Any help would be greatly appreciated and thanks for the plugin!

**Comment by alfredtan** [comment]
Hello. I'm having the same issue too. I'm piping through to another linter and the data is empty. 

Did you manage to find a solution for this?

**Comment by yvanavermaet** [comment]
My sincerest apologies, I have overlooked this issue completely.
I will take a look at it next week as I’m on holiday at the moment.

Kind regards,
Yannick

**Comment by alfredtan** [comment]
Thanks and enjoy your break!

**Comment by forrestab** [comment]
@alfredtan my only workaround is to continue using the previous version 0.0.14.
