### ISSUE TITLE
Could not process .htmllintrc.

### ISSUE THREAD

**Issue by johndavemanuel** [yvanavermaet/gulp-htmllint#28]
Hi!

I follow the documentation and I declare a file ".htmllintrc". It is same directory with gulpfile.js
but when I try to run it, it is error
`
 Could not process .htmllintrc. Using default htmllint configuration instead`

**Comment by yvanavermaet** [comment]
Hi

More than 1.5 years later, is this still an issue for you?
Apologies for not getting back to you sooner :-)

Kind regards,
Yannick

**Comment by johndavemanuel** [comment]
Hello!

Not anymore 👍 

Thanks
