### ISSUE TITLE
Please update to htmllint 0.8.0

### ISSUE THREAD

**Issue by e2tha-e** [yvanavermaet/gulp-htmllint#29]
Hi. I would like to incorporate htmllint 0.8.0 features into my usage of gulp-htmllint. Could you please update the htmllint dependency and release a new version of gulp-htmllint?

Thanks!

**Comment by yvanavermaet** [comment]
Hi

Since I'm not really using the package myself anymore, I did not really notice your issue.
I've just now released a new version 0.0.17 that uses htmllint 0.8.0.

Kind regards,
Yannick
