### ISSUE TITLE
htmllint options dose not work

### ISSUE THREAD

**Issue by mjasnikovs** [yvanavermaet/gulp-htmllint#5]
gulp.task('build-html', function() {
    gulp.src('./src/html/*.html')
        .pipe(htmllint({'line-end-style':false}, Reporter.htmlError))
        .pipe(gulpMinifyHtml())
        .pipe(gulp.dest('./build'));
});

I still get error "line ending does not match format: if"

**Comment by yvanavermaet** [comment]
@mjasnikovs My deepest apologies for replying so late.

It's not possible to pass along options in that way. Have a look at the documentation: https://github.com/yvanavermaet/gulp-htmllint

There are 3 options which you can pass along:
- config: path to a config file
- plugins: htmllint plugins to use
- failOnError: if true throw errorCode 1 on error

What you want to do, is create a config file (default it'll look for .htmllintrc) and put your options in there.
